module.exports = {
    // 'Bool': require('./Bool').Bool,
    'Bytearray': require('./Bytearray').Bytearray,
    'Bytes': require('./Bytes').Bytes,
    'Code': require('./Code').Code,
    'Complex': require('./Complex').Complex,
    'Dict': require('./Dict').Dict,
    'DictView': require('./DictView').DictView,
    'Ellipsis': require('./Ellipsis').Ellipsis,
    'filter': require('./Filter').filter,
    'Float': require('./Float').Float,
    'FrozenSet': require('./FrozenSet').FrozenSet,
    'Function': require('./Function').Function,
    'Method': require('./Function').Method,
    'Int': require('./Int').Int,
    'JSDict': require('./JSDict').JSDict,
    'List': require('./List').List,
    'map': require('./Map').map,
    'Module': require('./Module').Module,
    'NoneType': require('./NoneType').NoneType,
    'NotImplementedType': require('./NotImplementedType').NotImplementedType,
    'Range': require('./Range').Range,
    'Set': require('./Set').Set,
    'SetIterator': require('./SetIterator').SetIterator,
    'Slice': require('./Slice').Slice,
    'Str': require('./Str').Str,
    'Tuple': require('./Tuple').Tuple,
    'Type': require('./Type').Type,
    'Object': require('./Type').Object
}
