module.exports = {
    'Type': require('./Type').Type,
    'Object': require('./Type').Object,

    'Bool': require('./Bool'),
    'Bytearray': require('./Bytearray'),
    'Bytes': require('./Bytes'),
    'Code': require('./Code'),
    'Complex': require('./Complex'),
    'Dict': require('./Dict'),
    'DictView': require('./DictView'),
    'Ellipsis': require('./Ellipsis'),
    'filter': require('./Filter'),
    'Float': require('./Float'),
    'FrozenSet': require('./FrozenSet'),
    'Function': require('./Function'),
    'Generator': require('./Generator'),
    'Method': require('./Method'),
    'Int': require('./Int'),
    'JSDict': require('./JSDict'),
    'List': require('./List'),
    'map': require('./Map'),
    'Module': require('./Module'),
    'NoneType': require('./NoneType'),
    'NotImplementedType': require('./NotImplementedType'),
    'Range': require('./Range'),
    'Set': require('./Set'),
    'SetIterator': require('./SetIterator'),
    'Slice': require('./Slice'),
    'Str': require('./Str'),
    'Tuple': require('./Tuple')
}
