
// ouroboros source file colorsys.py compiled to pyc

/*
Copyright (c) 2016 Russell Keith-Magee.

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

    1. Redistributions of source code must retain the above copyright notice,
       this list of conditions and the following disclaimer.

    2. Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.

    3. Neither the name of Ouroboros nor the names of its contributors may
       be used to endorse or promote products derived from this software without
       specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


The original Python Standard Library, upon which this project is based, is
released under the terms of the PSF License version 2:

Copyright (c) 2001-2014 Python Software Foundation; All rights reserved

PYTHON SOFTWARE FOUNDATION LICENSE VERSION 2
--------------------------------------------

1. This LICENSE AGREEMENT is between the Python Software Foundation
("PSF"), and the Individual or Organization ("Licensee") accessing and
otherwise using this software ("Python") in source or binary form and
its associated documentation.

2. Subject to the terms and conditions of this License Agreement, PSF hereby
grants Licensee a nonexclusive, royalty-free, world-wide license to reproduce,
analyze, test, perform and/or display publicly, prepare derivative works,
distribute, and otherwise use Python alone or in any derivative version,
provided, however, that PSF's License Agreement and PSF's notice of copyright,
i.e., "Copyright (c) 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
2011, 2012, 2013, 2014 Python Software Foundation; All Rights Reserved" are
retained in Python alone or in any derivative version prepared by Licensee.

3. In the event Licensee prepares a derivative work that is based on
or incorporates Python or any part thereof, and wants to make
the derivative work available to others as provided herein, then
Licensee hereby agrees to include in any such work a brief summary of
the changes made to Python.

4. PSF is making Python available to Licensee on an "AS IS"
basis.  PSF MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR
IMPLIED.  BY WAY OF EXAMPLE, BUT NOT LIMITATION, PSF MAKES NO AND
DISCLAIMS ANY REPRESENTATION OR WARRANTY OF MERCHANTABILITY OR FITNESS
FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF PYTHON WILL NOT
INFRINGE ANY THIRD PARTY RIGHTS.

5. PSF SHALL NOT BE LIABLE TO LICENSEE OR ANY OTHER USERS OF PYTHON
FOR ANY INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR LOSS AS
A RESULT OF MODIFYING, DISTRIBUTING, OR OTHERWISE USING PYTHON,
OR ANY DERIVATIVE THEREOF, EVEN IF ADVISED OF THE POSSIBILITY THEREOF.

6. This License Agreement will automatically terminate upon a material
breach of its terms and conditions.

7. Nothing in this License Agreement shall be deemed to create any
relationship of agency, partnership, or joint venture between PSF and
Licensee.  This License Agreement does not grant permission to use PSF
trademarks or trade name in a trademark sense to endorse or promote
products or services of Licensee, or any third party.

8. By copying, installing or otherwise using Python, Licensee
agrees to be bound by the terms and conditions of this License
Agreement.
*/
batavia.stdlib['colorsys'] = 'Fg0NCnAUy1fgDwAA4wAAAAAAAAAAAAAAAAYAAABAAAAAc4gAAABkAABaAABkAQBkAgBkAwBkBABkBQBkBgBnBgBaAQBkFABaAgBkFQBaAwBkFgBaBABkCwBkAQCEAABaBQBkDABkAgCEAABaBgBkDQBkAwCEAABaBwBkDgBkBACEAABaCABkDwBkEACEAABaCQBkEQBkBQCEAABaCgBkEgBkBgCEAABaCwBkEwBTKRdhSgIAAENvbnZlcnNpb24gZnVuY3Rpb25zIGJldHdlZW4gUkdCIGFuZCBvdGhlciBjb2xvciBzeXN0ZW1zLgoKVGhpcyBtb2R1bGVzIHByb3ZpZGVzIHR3byBmdW5jdGlvbnMgZm9yIGVhY2ggY29sb3Igc3lzdGVtIEFCQzoKCiAgcmdiX3RvX2FiYyhyLCBnLCBiKSAtLT4gYSwgYiwgYwogIGFiY190b19yZ2IoYSwgYiwgYykgLS0+IHIsIGcsIGIKCkFsbCBpbnB1dHMgYW5kIG91dHB1dHMgYXJlIHRyaXBsZXMgb2YgZmxvYXRzIGluIHRoZSByYW5nZSBbMC4wLi4uMS4wXQood2l0aCB0aGUgZXhjZXB0aW9uIG9mIEkgYW5kIFEsIHdoaWNoIGNvdmVycyBhIHNsaWdodGx5IGxhcmdlciByYW5nZSkuCklucHV0cyBvdXRzaWRlIHRoZSB2YWxpZCByYW5nZSBtYXkgY2F1c2UgZXhjZXB0aW9ucyBvciBpbnZhbGlkIG91dHB1dHMuCgpTdXBwb3J0ZWQgY29sb3Igc3lzdGVtczoKUkdCOiBSZWQsIEdyZWVuLCBCbHVlIGNvbXBvbmVudHMKWUlROiBMdW1pbmFuY2UsIENocm9taW5hbmNlICh1c2VkIGJ5IGNvbXBvc2l0ZSB2aWRlbyBzaWduYWxzKQpITFM6IEh1ZSwgTHVtaW5hbmNlLCBTYXR1cmF0aW9uCkhTVjogSHVlLCBTYXR1cmF0aW9uLCBWYWx1ZQraCnJnYl90b195aXHaCnlpcV90b19yZ2LaCnJnYl90b19obHPaCmhsc190b19yZ2LaCnJnYl90b19oc3baCmhzdl90b19yZ2JnAAAAAAAA8D9nAAAAAAAACEBnAAAAAAAAGEBnAAAAAAAAAEBjAwAAAAAAAAAGAAAABAAAAEMAAABzWwAAAGQBAHwAABRkAgB8AQAUF2QDAHwCABQXfQMAZAQAfAAAfAMAGBRkBQB8AgB8AwAYFBh9BABkBgB8AAB8AwAYFGQHAHwCAHwDABgUF30FAHwDAHwEAHwFAGYDAFMpCE5nMzMzMzMz0z9n4XoUrkfh4j9nKVyPwvUovD9nrkfhehSu5z9nSOF6FK5H0T9nuB6F61G43j9nPQrXo3A92j+pACkG2gFy2gFn2gFi2gF52gFp2gFxcgcAAAByBwAAAPoiLi4vb3Vyb2Jvcm9zL291cm9ib3Jvcy9jb2xvcnN5cy5weXIBAAAAKAAAAHMIAAAAAAEaARoBGgFjAwAAAAAAAAAGAAAAAwAAAEMAAABzuwAAAHwAAGQBAHwBABQXZAIAfAIAFBd9AwB8AABkAwB8AQAUGGQEAHwCABQYfQQAfAAAZAUAfAEAFBhkBgB8AgAUF30FAHwDAGQHAGsAAHJUAGQHAH0DAHwEAGQHAGsAAHJmAGQHAH0EAHwFAGQHAGsAAHJ4AGQHAH0FAHwDAGQIAGsEAHKKAGQIAH0DAHwEAGQIAGsEAHKcAGQIAH0EAHwFAGQIAGsEAHKuAGQIAH0FAHwDAHwEAHwFAGYDAFMpCU5nMhty79tM7j9nvsDa7iz04z9nOruM7B6W0T9n8/9u0ZRX5D9nNuTet5m88T9nf0oiphdY+z9nAAAAAAAAAABnAAAAAAAA8D9yBwAAACkGcgsAAAByDAAAAHINAAAAcggAAAByCQAAAHIKAAAAcgcAAAByBwAAAHIOAAAAcgIAAAAuAAAAcyAAAAAABRYBFgEWAgwBBgEMAQYBDAEGAQwBBgEMAQYBDAEGAWMDAAAAAAAAAAsAAAAEAAAAQwAAAHMXAQAAdAAAfAAAfAEAfAIAgwMAfQMAdAEAfAAAfAEAfAIAgwMAfQQAfAQAfAMAF2QBABt9BQB8BAB8AwBrAgBySwBkAgB8BQBkAgBmAwBTfAUAZAMAawEAcmwAfAMAfAQAGHwDAHwEABcbfQYAbhYAfAMAfAQAGGQBAHwDABh8BAAYG30GAHwDAHwAABh8AwB8BAAYG30HAHwDAHwBABh8AwB8BAAYG30IAHwDAHwCABh8AwB8BAAYG30JAHwAAHwDAGsCAHLRAHwJAHwIABh9CgBuKwB8AQB8AwBrAgBy7gBkAQB8BwAXfAkAGH0KAG4OAGQEAHwIABd8BwAYfQoAfAoAZAUAG2QGABZ9CgB8CgB8BQB8BgBmAwBTKQdOZwAAAAAAAABAZwAAAAAAAAAAZwAAAAAAAOA/ZwAAAAAAABBAZwAAAAAAABhAZwAAAAAAAPA/KQLaA21heNoDbWluKQtyCAAAAHIJAAAAcgoAAADaBG1heGPaBG1pbmPaAWzaAXPaAnJj2gJnY9oCYmPaAWhyBwAAAHIHAAAAcg4AAAByAwAAAEsAAABzJAAAAAABEgESAg4BDAENAQwBFQIWARIBEgESAQwBDQEMARECDgEOAWMDAAAAAAAAAAUAAAAHAAAAQwAAAHOPAAAAfAIAZAEAawIAchkAfAEAfAEAfAEAZgMAU3wBAGQCAGsBAHI2AHwBAGQDAHwCABcUfQMAbhIAfAEAfAIAF3wBAHwCABQYfQMAZAQAfAEAFHwDABh9BAB0AAB8BAB8AwB8AAB0AQAXgwMAdAAAfAQAfAMAfAAAgwMAdAAAfAQAfAMAfAAAdAEAGIMDAGYDAFMpBU5nAAAAAAAAAABnAAAAAAAA4D9nAAAAAAAA8D9nAAAAAAAAAEApAtoCX3baCU9ORV9USElSRCkFchgAAAByEwAAAHIUAAAA2gJtMtoCbTFyBwAAAHIHAAAAcg4AAAByBAAAAGIAAABzDgAAAAABDAENAQwBEQISAQ4BYwMAAAAAAAAAAwAAAAQAAABDAAAAc2IAAAB8AgBkAQAWfQIAfAIAdAAAawAAcioAfAAAfAEAfAAAGHwCABRkAgAUF1N8AgBkAwBrAAByOgB8AQBTfAIAdAEAawAAcl4AfAAAfAEAfAAAGHQBAHwCABgUZAIAFBdTfAAAUykETmcAAAAAAADwP2cAAAAAAAAYQGcAAAAAAADgPykC2glPTkVfU0lYVEjaCVRXT19USElSRCkDchwAAAByGwAAAFoDaHVlcgcAAAByBwAAAHIOAAAAchkAAABsAAAAcxAAAAAAAQoBDAEUAQwBBAEMARgBchkAAABjAwAAAAAAAAALAAAABAAAAEMAAABz5gAAAHQAAHwAAHwBAHwCAIMDAH0DAHQBAHwAAHwBAHwCAIMDAH0EAHwDAH0FAHwEAHwDAGsCAHJDAGQBAGQBAHwFAGYDAFN8AwB8BAAYfAMAG30GAHwDAHwAABh8AwB8BAAYG30HAHwDAHwBABh8AwB8BAAYG30IAHwDAHwCABh8AwB8BAAYG30JAHwAAHwDAGsCAHKgAHwJAHwIABh9CgBuKwB8AQB8AwBrAgByvQBkAgB8BwAXfAkAGH0KAG4OAGQDAHwIABd8BwAYfQoAfAoAZAQAG2QFABZ9CgB8CgB8BgB8BQBmAwBTKQZOZwAAAAAAAAAAZwAAAAAAAABAZwAAAAAAABBAZwAAAAAAABhAZwAAAAAAAPA/KQJyDwAAAHIQAAAAKQtyCAAAAHIJAAAAcgoAAAByEQAAAHISAAAA2gF2chQAAAByFQAAAHIWAAAAchcAAAByGAAAAHIHAAAAcgcAAAByDgAAAHIFAAAAfAAAAHMgAAAAAAESARIBBgEMAQ0BDgESARIBEgEMAQ0BDAERAg4BDgFjAwAAAAAAAAAIAAAABQAAAEMAAABzEQEAAHwBAGQBAGsCAHIZAHwCAHwCAHwCAGYDAFN0AAB8AABkAgAUgwEAfQMAfAAAZAIAFHwDABh9BAB8AgBkAwB8AQAYFH0FAHwCAGQDAHwBAHwEABQYFH0GAHwCAGQDAHwBAGQDAHwEABgUGBR9BwB8AwBkBAAWfQMAfAMAZAUAawIAcpAAfAIAfAcAfAUAZgMAU3wDAGQGAGsCAHKpAHwGAHwCAHwFAGYDAFN8AwBkBwBrAgBywgB8BQB8AgB8BwBmAwBTfAMAZAgAawIActsAfAUAfAYAfAIAZgMAU3wDAGQJAGsCAHL0AHwHAHwFAHwCAGYDAFN8AwBkCgBrAgByDQF8AgB8BQB8BgBmAwBTZAAAUykLTmcAAAAAAAAAAGcAAAAAAAAYQGcAAAAAAADwP+kGAAAA6QAAAADpAQAAAOkCAAAA6QMAAADpBAAAAOkFAAAAKQHaA2ludCkIchgAAAByFAAAAHIfAAAAcgwAAADaAWbaAXByDQAAANoBdHIHAAAAcgcAAAByDgAAAHIGAAAAjwAAAHMoAAAAAAEMAQ0BEAEOAQ4BEgEWAQoBDAENAQwBDQEMAQ0BDAENAQwBDQEMAU5nVVVVVVVV1T9nVVVVVVVVxT9nVVVVVVVV5T8pDNoHX19kb2NfX9oHX19hbGxfX3IaAAAAch0AAAByHgAAAHIBAAAAcgIAAAByAwAAAHIEAAAAchkAAAByBQAAAHIGAAAAcgcAAAByBwAAAHIHAAAAcg4AAADaCDxtb2R1bGU+EQAAAHMYAAAABgcMAQwEBgEGAQYJDAYMHQwXDAoMEAwT';
